#!/usr/bin/bash

bssid=$(nmcli device wifi list | sed -n '1!p' | cut -b 9- | dmenu -p "select wifi:" -l 10 | cut -d' ' -f1)
pass=$(echo "" | dmenu -p "enter password")
nmcli device wifi connect $bssid password $pass
